SET TIMING ON;
--PERFORMANCE TUNING QUESTION 1
SELECT YEAR,COUNT(*)AS TOTAL_FEMALE_CANDIDATE
FROM ELECTION WHERE CAND_SEX='F'
GROUP BY YEAR;
--PERFORMANCE TUNING QUESTION 2
SELECT YEAR,ST_NAME,COUNT(*)AS TOTAL
FROM ELECTION GROUP BY YEAR,ST_NAME;
--PERFORMANCE TUNING QUESTION 3
SELECT YEAR,SUM(TOTVOTPOLL)AS TOTAL
FROM ELECTION WHERE YEAR =1987 AND PARTYNAME='BJP'
GROUP BY YEAR;
--PERFORMANCE TUNING QUESTION 4
SELECT ST_NAME,COUNT(*)AS TOTAL
FROM ELECTION WHERE YEAR=2004
GROUP BY ST_NAME;
--PERFORMANCE TUNING QUESTION 5
SELECT PARTYNAME FROM
(SELECT PARTYNAME,SUM(TOTVOTPOLL)AS VOTES
FROM ELECTION WHERE YEAR=2014 AND ST_NAME='Uttar Pradesh'
GROUP BY PARTYNAME)
ORDER BY VOTES DESC FETCH FIRST 5 ROWS ONLY;