SET TIMING ON;

--SQL QUERY 1
SELECT YEAR, COUNT(*) 
AS FEMALE_CANDIDATE
FROM ELECTION
WHERE CAND_SEX='F'
GROUP BY YEAR;


--SQL QUERY 2
SELECT YEAR, ST_NAME, COUNT(*)
AS TOTAL_CANDIDATE
FROM ELECTION
GROUP BY YEAR,ST_NAME;


--SQL QUERY 3
SELECT YEAR, SUM(TOTVOTPOLL)
AS TOTAL_MEMBERS
FROM ELECTION
WHERE YEAR=1987 AND PARTYNAME='BJP'
GROUP BY YEAR;


--SQL QUERY 4
SELECT ST_NAME,COUNT(*)
AS TOTAL_MEMBERS
FROM ELECTION
WHERE YEAR=2004
GROUP BY ST_NAME;

--SQL QUERY 5
SELECT PARTYNAME
FROM (
    SELECT PARTYNAME,SUM(TOTVOTPOLL)
    AS VOTE_NUMBER
    FROM ELECTION
    WHERE YEAR=2014 AND ST_NAME='UTTAR PRADESH'
    GROUP BY PARTYNAME
)
ORDER BY VOTE_NUMBER DESC
FETCH FIRST 5 ROWS ONLY;